namespace PeerstPlayer.Controls.MoviePlayer
{
	partial class FlashMoviePlayerControl
	{
		/// <summary> 
		/// Required designer variables.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up all resources in use.
		/// </summary>
		/// <param name="disposing">True if the managed resource is destroyed, false if it is not.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Code generated by the component designer

		/// <summary> 
		/// This method is required for designer support. The contents of this method
		/// Do not change it in the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FlashMoviePlayerControl));
			this.axShockwaveFlash = new AxShockwaveFlashObjects.AxShockwaveFlash();
			((System.ComponentModel.ISupportInitialize)(this.axShockwaveFlash)).BeginInit();
			this.SuspendLayout();
			// 
			// axShockwaveFlash
			// 
			this.axShockwaveFlash.Dock = System.Windows.Forms.DockStyle.Fill;
			this.axShockwaveFlash.Enabled = true;
			this.axShockwaveFlash.Location = new System.Drawing.Point(0, 0);
			this.axShockwaveFlash.Name = "axShockwaveFlash";
			this.axShockwaveFlash.OcxState = ((System.Windows.Forms.AxHost.State)(resources.GetObject("axShockwaveFlash.OcxState")));
			this.axShockwaveFlash.Size = new System.Drawing.Size(150, 150);
			this.axShockwaveFlash.TabIndex = 0;
			// 
			// FlashMoviePlayerControl
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.Black;
			this.Controls.Add(this.axShockwaveFlash);
			this.Name = "FlashMoviePlayerControl";
			((System.ComponentModel.ISupportInitialize)(this.axShockwaveFlash)).EndInit();
			this.ResumeLayout(false);
		}

		#endregion

		private AxShockwaveFlashObjects.AxShockwaveFlash axShockwaveFlash;
	}
}
