//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
//[assembly: System.Windows.Forms.AxHost.TypeLibraryTimeStamp("6/11/2007 1:15:36 PM")]

using System.Runtime.InteropServices;

namespace WalkerPlayer {


    [System.Windows.Forms.AxHost.ClsidAttribute("{d27cdb6e-ae6d-11cf-96b8-444553540000}")]
    [System.ComponentModel.DesignTimeVisibleAttribute(true)]
    public class AxShockwaveFlash : System.Windows.Forms.AxHost {

        private WalkerPlayer.IShockwaveFlash ocx;

        private AxShockwaveFlashEventMulticaster eventMulticaster;

        private System.Windows.Forms.AxHost.ConnectionPointCookie cookie;

        public AxShockwaveFlash() :
                base("d27cdb6e-ae6d-11cf-96b8-444553540000") {
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(-525)]
        public virtual int ReadyState {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ReadyState", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.ReadyState;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(124)]
        public virtual int TotalFrames {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TotalFrames", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.TotalFrames;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(125)]
        public virtual bool Playing {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Playing", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Playing;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Playing", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Playing = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(105)]
        public virtual int Quality {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Quality", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Quality;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Quality", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Quality = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(120)]
        public virtual int ScaleMode {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ScaleMode", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.ScaleMode;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ScaleMode", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.ScaleMode = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(121)]
        public virtual int AlignMode {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AlignMode", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.AlignMode;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AlignMode", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.AlignMode = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(123)]
        public virtual int BackgroundColor {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("BackgroundColor", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.BackgroundColor;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("BackgroundColor", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.BackgroundColor = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(106)]
        public virtual bool Loop {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Loop", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Loop;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Loop", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Loop = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(102)]
        public virtual string Movie {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Movie", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Movie;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Movie", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Movie = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(107)]
        public virtual int FrameNum {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("FrameNum", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.FrameNum;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("FrameNum", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.FrameNum = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(133)]
        public virtual string WMode {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("WMode", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.WMode;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("WMode", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.WMode = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(134)]
        public virtual string SAlign {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SAlign", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.SAlign;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SAlign", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.SAlign = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(135)]
        public virtual bool Menu {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Menu", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Menu;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Menu", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Menu = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(136)]
        public virtual string Base {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Base", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Base;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Base", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Base = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(137)]
        public virtual string CtlScale {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("CtlScale", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Scale;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("CtlScale", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Scale = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(138)]
        public virtual bool DeviceFont {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("DeviceFont", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.DeviceFont;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("DeviceFont", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.DeviceFont = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(139)]
        public virtual bool EmbedMovie {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("EmbedMovie", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.EmbedMovie;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("EmbedMovie", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.EmbedMovie = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(140)]
        public virtual string BGColor {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("BGColor", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.BGColor;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("BGColor", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.BGColor = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(141)]
        public virtual string Quality2 {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Quality2", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Quality2;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Quality2", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Quality2 = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(159)]
        public virtual string SWRemote {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SWRemote", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.SWRemote;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SWRemote", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.SWRemote = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(170)]
        public virtual string FlashVars {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("FlashVars", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.FlashVars;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("FlashVars", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.FlashVars = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(171)]
        public virtual string AllowScriptAccess {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AllowScriptAccess", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.AllowScriptAccess;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AllowScriptAccess", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.AllowScriptAccess = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(190)]
        public virtual string MovieData {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("MovieData", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.MovieData;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("MovieData", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.MovieData = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(191)]
        public virtual object InlineData {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("InlineData", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.InlineData;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("InlineData", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.InlineData = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(192)]
        public virtual bool SeamlessTabbing {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SeamlessTabbing", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.SeamlessTabbing;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SeamlessTabbing", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.SeamlessTabbing = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(194)]
        public virtual bool Profile {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Profile", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Profile;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Profile", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Profile = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(195)]
        public virtual string ProfileAddress {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ProfileAddress", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.ProfileAddress;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ProfileAddress", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.ProfileAddress = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(196)]
        public virtual int ProfilePort {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ProfilePort", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.ProfilePort;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ProfilePort", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.ProfilePort = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(201)]
        public virtual string AllowNetworking {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AllowNetworking", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.AllowNetworking;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AllowNetworking", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.AllowNetworking = value;
            }
        }

        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(202)]
        public virtual string AllowFullScreen {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AllowFullScreen", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.AllowFullScreen;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("AllowFullScreen", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.AllowFullScreen = value;
            }
        }

        public event _IShockwaveFlashEvents_OnReadyStateChangeEventHandler OnReadyStateChange;

        public event _IShockwaveFlashEvents_OnProgressEventHandler OnProgress;

        public event _IShockwaveFlashEvents_FSCommandEventHandler FSCommand;

        public event _IShockwaveFlashEvents_FlashCallEventHandler FlashCall;

        public virtual void TCallLabel(string target, string label) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TCallLabel", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TCallLabel(target, label);
        }

        public virtual void TSetPropertyNum(string target, int property, double value) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TSetPropertyNum", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TSetPropertyNum(target, property, value);
        }

        public virtual double TGetPropertyNum(string target, int property) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TGetPropertyNum", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            double returnValue = ((double)(this.ocx.TGetPropertyNum(target, property)));
            return returnValue;
        }

        public virtual double TGetPropertyAsNumber(string target, int property) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TGetPropertyAsNumber", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            double returnValue = ((double)(this.ocx.TGetPropertyAsNumber(target, property)));
            return returnValue;
        }

        public virtual void EnforceLocalSecurity() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("EnforceLocalSecurity", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.EnforceLocalSecurity();
        }

        public virtual string CallFunction(string request) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("CallFunction", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            string returnValue = ((string)(this.ocx.CallFunction(request)));
            return returnValue;
        }

        public virtual void SetReturnValue(string returnValue) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SetReturnValue", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.SetReturnValue(returnValue);
        }

        public virtual void DisableLocalSecurity() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("DisableLocalSecurity", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.DisableLocalSecurity();
        }

        public virtual void SetZoomRect(int left, int top, int right, int bottom) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SetZoomRect", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.SetZoomRect(left, top, right, bottom);
        }

        public virtual void Zoom(int factor) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Zoom", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Zoom(factor);
        }

        public virtual void Pan(int x, int y, int mode) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Pan", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Pan(x, y, mode);
        }

        public virtual void Play() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Play", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Play();
        }

        public virtual void Stop() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Stop", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Stop();
        }

        public virtual void Back() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Back", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Back();
        }

        public virtual void Forward() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Forward", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Forward();
        }

        public virtual void Rewind() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Rewind", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.Rewind();
        }

        public virtual void StopPlay() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("StopPlay", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.StopPlay();
        }

        public virtual void GotoFrame(int frameNum) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("GotoFrame", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.GotoFrame(frameNum);
        }

        public virtual int CurrentFrame() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("CurrentFrame", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            int returnValue = ((int)(this.ocx.CurrentFrame()));
            return returnValue;
        }

        public virtual bool IsPlaying() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("IsPlaying", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            bool returnValue = ((bool)(this.ocx.IsPlaying()));
            return returnValue;
        }

        public virtual int PercentLoaded() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("PercentLoaded", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            int returnValue = ((int)(this.ocx.PercentLoaded()));
            return returnValue;
        }

        public virtual bool FrameLoaded(int frameNum) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("FrameLoaded", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            bool returnValue = ((bool)(this.ocx.FrameLoaded(frameNum)));
            return returnValue;
        }

        public virtual int FlashVersion() {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("FlashVersion", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            int returnValue = ((int)(this.ocx.FlashVersion()));
            return returnValue;
        }

        public virtual void LoadMovie(int layer, string url) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("LoadMovie", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.LoadMovie(layer, url);
        }

        public virtual void TGotoFrame(string target, int frameNum) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TGotoFrame", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TGotoFrame(target, frameNum);
        }

        public virtual void TGotoLabel(string target, string label) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TGotoLabel", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TGotoLabel(target, label);
        }

        public virtual int TCurrentFrame(string target) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TCurrentFrame", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            int returnValue = ((int)(this.ocx.TCurrentFrame(target)));
            return returnValue;
        }

        public virtual string TCurrentLabel(string target) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TCurrentLabel", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            string returnValue = ((string)(this.ocx.TCurrentLabel(target)));
            return returnValue;
        }

        public virtual void TPlay(string target) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TPlay", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TPlay(target);
        }

        public virtual void TStopPlay(string target) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TStopPlay", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TStopPlay(target);
        }

        public virtual void SetVariable(string name, string value) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("SetVariable", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.SetVariable(name, value);
        }

        public virtual string GetVariable(string name) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("GetVariable", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            string returnValue = ((string)(this.ocx.GetVariable(name)));
            return returnValue;
        }

        public virtual void TSetProperty(string target, int property, string value) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TSetProperty", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TSetProperty(target, property, value);
        }

        public virtual string TGetProperty(string target, int property) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TGetProperty", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            string returnValue = ((string)(this.ocx.TGetProperty(target, property)));
            return returnValue;
        }

        public virtual void TCallFrame(string target, int frameNum) {
            if ((this.ocx == null)) {
                throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("TCallFrame", System.Windows.Forms.AxHost.ActiveXInvokeKind.MethodInvoke);
            }
            this.ocx.TCallFrame(target, frameNum);
        }

        protected override void CreateSink() {
            try {
                this.eventMulticaster = new AxShockwaveFlashEventMulticaster(this);
                this.cookie = new System.Windows.Forms.AxHost.ConnectionPointCookie(this.ocx, this.eventMulticaster, typeof(WalkerPlayer.IIShockwaveFlashEvents));
            }
            catch (System.Exception) {
            }
        }

        protected override void DetachSink() {
            try {
                this.cookie.Disconnect();
            }
            catch (System.Exception) {
            }
        }

        protected override void AttachInterfaces() {
            try {
                this.ocx = ((WalkerPlayer.IShockwaveFlash)(this.GetOcx()));
            }
            catch (System.Exception) {
            }
        }

        internal void RaiseOnOnReadyStateChange(object sender, _IShockwaveFlashEvents_OnReadyStateChangeEvent e) {
            if ((this.OnReadyStateChange != null)) {
                this.OnReadyStateChange(sender, e);
            }
        }

        internal void RaiseOnOnProgress(object sender, _IShockwaveFlashEvents_OnProgressEvent e) {
            if ((this.OnProgress != null)) {
                this.OnProgress(sender, e);
            }
        }

        internal void RaiseOnFSCommand(object sender, _IShockwaveFlashEvents_FSCommandEvent e) {
            if ((this.FSCommand != null)) {
                this.FSCommand(sender, e);
            }
        }

        internal void RaiseOnFlashCall(object sender, _IShockwaveFlashEvents_FlashCallEvent e) {
            if ((this.FlashCall != null)) {
                this.FlashCall(sender, e);
            }
        }
    }

    public delegate void _IShockwaveFlashEvents_OnReadyStateChangeEventHandler(object sender, _IShockwaveFlashEvents_OnReadyStateChangeEvent e);

    public class _IShockwaveFlashEvents_OnReadyStateChangeEvent {

        public int newState;

        public _IShockwaveFlashEvents_OnReadyStateChangeEvent(int newState) {
            this.newState = newState;
        }
    }

    public delegate void _IShockwaveFlashEvents_OnProgressEventHandler(object sender, _IShockwaveFlashEvents_OnProgressEvent e);

    public class _IShockwaveFlashEvents_OnProgressEvent {

        public int percentDone;

        public _IShockwaveFlashEvents_OnProgressEvent(int percentDone) {
            this.percentDone = percentDone;
        }
    }

    public delegate void _IShockwaveFlashEvents_FSCommandEventHandler(object sender, _IShockwaveFlashEvents_FSCommandEvent e);

    public class _IShockwaveFlashEvents_FSCommandEvent {

        public string command;

        public string args;

        public _IShockwaveFlashEvents_FSCommandEvent(string command, string args) {
            this.command = command;
            this.args = args;
        }
    }

    public delegate void _IShockwaveFlashEvents_FlashCallEventHandler(object sender, _IShockwaveFlashEvents_FlashCallEvent e);

    public class _IShockwaveFlashEvents_FlashCallEvent {

        public string request;

        public _IShockwaveFlashEvents_FlashCallEvent(string request) {
            this.request = request;
        }
    }

    [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)]
    public class AxShockwaveFlashEventMulticaster : WalkerPlayer.IIShockwaveFlashEvents {

        private AxShockwaveFlash parent;

        public AxShockwaveFlashEventMulticaster(AxShockwaveFlash parent) {
            this.parent = parent;
        }

        public virtual void OnReadyStateChange(int newState) {
            _IShockwaveFlashEvents_OnReadyStateChangeEvent onreadystatechangeEvent = new _IShockwaveFlashEvents_OnReadyStateChangeEvent(newState);
            this.parent.RaiseOnOnReadyStateChange(this.parent, onreadystatechangeEvent);
        }

        public virtual void OnProgress(int percentDone) {
            _IShockwaveFlashEvents_OnProgressEvent onprogressEvent = new _IShockwaveFlashEvents_OnProgressEvent(percentDone);
            this.parent.RaiseOnOnProgress(this.parent, onprogressEvent);
        }

        public virtual void FSCommand(string command, string args) {
            _IShockwaveFlashEvents_FSCommandEvent fscommandEvent = new _IShockwaveFlashEvents_FSCommandEvent(command, args);
            this.parent.RaiseOnFSCommand(this.parent, fscommandEvent);
        }

        public virtual void FlashCall(string request) {
            _IShockwaveFlashEvents_FlashCallEvent flashcallEvent = new _IShockwaveFlashEvents_FlashCallEvent(request);
            this.parent.RaiseOnFlashCall(this.parent, flashcallEvent);
        }
    }
    /// <summary><para><c>IShockwaveFlash</c> interface.  </para><para>Shockwave Flash</para></summary>
    // Shockwave Flash
    [Guid("D27CDB6C-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [TypeLibType((short)4160)]
    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IShockwaveFlash {
        /// <summary><para><c>SetZoomRect</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method SetZoomRect</para></summary>
        /// <remarks><para>An original IDL definition of <c>SetZoomRect</c> method was the following:  <c>HRESULT SetZoomRect (long left, long top, long right, long bottom)</c>;</para></remarks>
        // method SetZoomRect
        // IDL: HRESULT SetZoomRect (long left, long top, long right, long bottom);
        // VB6: Sub SetZoomRect (ByVal left As Long, ByVal top As Long, ByVal right As Long, ByVal bottom As Long)
        [DispId(109)]
        void SetZoomRect(int left, int top, int right, int bottom);

        /// <summary><para><c>Zoom</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Zoom</para></summary>
        /// <remarks><para>An original IDL definition of <c>Zoom</c> method was the following:  <c>HRESULT Zoom (int factor)</c>;</para></remarks>
        // method Zoom
        // IDL: HRESULT Zoom (int factor);
        // VB6: Sub Zoom (ByVal factor As Long)
        [DispId(118)]
        void Zoom(int factor);

        /// <summary><para><c>Pan</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Pan</para></summary>
        /// <remarks><para>An original IDL definition of <c>Pan</c> method was the following:  <c>HRESULT Pan (long x, long y, int mode)</c>;</para></remarks>
        // method Pan
        // IDL: HRESULT Pan (long x, long y, int mode);
        // VB6: Sub Pan (ByVal x As Long, ByVal y As Long, ByVal mode As Long)
        [DispId(119)]
        void Pan(int x, int y, int mode);

        /// <summary><para><c>Play</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Play</para></summary>
        /// <remarks><para>An original IDL definition of <c>Play</c> method was the following:  <c>HRESULT Play (void)</c>;</para></remarks>
        // method Play
        // IDL: HRESULT Play (void);
        // VB6: Sub Play
        [DispId(112)]
        void Play();

        /// <summary><para><c>Stop</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Stop</para></summary>
        /// <remarks><para>An original IDL definition of <c>Stop</c> method was the following:  <c>HRESULT Stop (void)</c>;</para></remarks>
        // method Stop
        // IDL: HRESULT Stop (void);
        // VB6: Sub Stop
        [DispId(113)]
        void Stop();

        /// <summary><para><c>Back</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Back</para></summary>
        /// <remarks><para>An original IDL definition of <c>Back</c> method was the following:  <c>HRESULT Back (void)</c>;</para></remarks>
        // method Back
        // IDL: HRESULT Back (void);
        // VB6: Sub Back
        [DispId(114)]
        void Back();

        /// <summary><para><c>Forward</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Forward</para></summary>
        /// <remarks><para>An original IDL definition of <c>Forward</c> method was the following:  <c>HRESULT Forward (void)</c>;</para></remarks>
        // method Forward
        // IDL: HRESULT Forward (void);
        // VB6: Sub Forward
        [DispId(115)]
        void Forward();

        /// <summary><para><c>Rewind</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Rewind</para></summary>
        /// <remarks><para>An original IDL definition of <c>Rewind</c> method was the following:  <c>HRESULT Rewind (void)</c>;</para></remarks>
        // method Rewind
        // IDL: HRESULT Rewind (void);
        // VB6: Sub Rewind
        [DispId(116)]
        void Rewind();

        /// <summary><para><c>StopPlay</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method StopPlay</para></summary>
        /// <remarks><para>An original IDL definition of <c>StopPlay</c> method was the following:  <c>HRESULT StopPlay (void)</c>;</para></remarks>
        // method StopPlay
        // IDL: HRESULT StopPlay (void);
        // VB6: Sub StopPlay
        [DispId(126)]
        void StopPlay();

        /// <summary><para><c>GotoFrame</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method GotoFrame</para></summary>
        /// <remarks><para>An original IDL definition of <c>GotoFrame</c> method was the following:  <c>HRESULT GotoFrame (long FrameNum)</c>;</para></remarks>
        // method GotoFrame
        // IDL: HRESULT GotoFrame (long FrameNum);
        // VB6: Sub GotoFrame (ByVal FrameNum As Long)
        [DispId(127)]
        void GotoFrame(int FrameNum);

        /// <summary><para><c>CurrentFrame</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method CurrentFrame</para></summary>
        /// <remarks><para>An original IDL definition of <c>CurrentFrame</c> method was the following:  <c>HRESULT CurrentFrame ([out, retval] long* ReturnValue)</c>;</para></remarks>
        // method CurrentFrame
        // IDL: HRESULT CurrentFrame ([out, retval] long* ReturnValue);
        // VB6: Function CurrentFrame As Long
        [DispId(128)]
        int CurrentFrame();

        /// <summary><para><c>IsPlaying</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method IsPlaying</para></summary>
        /// <remarks><para>An original IDL definition of <c>IsPlaying</c> method was the following:  <c>HRESULT IsPlaying ([out, retval] VARIANT_BOOL* ReturnValue)</c>;</para></remarks>
        // method IsPlaying
        // IDL: HRESULT IsPlaying ([out, retval] VARIANT_BOOL* ReturnValue);
        // VB6: Function IsPlaying As Boolean
        [DispId(129)]
        [return: MarshalAs(UnmanagedType.VariantBool)]
        bool IsPlaying();

        /// <summary><para><c>PercentLoaded</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method PercentLoaded</para></summary>
        /// <remarks><para>An original IDL definition of <c>PercentLoaded</c> method was the following:  <c>HRESULT PercentLoaded ([out, retval] long* ReturnValue)</c>;</para></remarks>
        // method PercentLoaded
        // IDL: HRESULT PercentLoaded ([out, retval] long* ReturnValue);
        // VB6: Function PercentLoaded As Long
        [DispId(130)]
        int PercentLoaded();

        /// <summary><para><c>FrameLoaded</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method FrameLoaded</para></summary>
        /// <remarks><para>An original IDL definition of <c>FrameLoaded</c> method was the following:  <c>HRESULT FrameLoaded (long FrameNum, [out, retval] VARIANT_BOOL* ReturnValue)</c>;</para></remarks>
        // method FrameLoaded
        // IDL: HRESULT FrameLoaded (long FrameNum, [out, retval] VARIANT_BOOL* ReturnValue);
        // VB6: Function FrameLoaded (ByVal FrameNum As Long) As Boolean
        [DispId(131)]
        [return: MarshalAs(UnmanagedType.VariantBool)]
        bool FrameLoaded(int FrameNum);

        /// <summary><para><c>FlashVersion</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method FlashVersion</para></summary>
        /// <remarks><para>An original IDL definition of <c>FlashVersion</c> method was the following:  <c>HRESULT FlashVersion ([out, retval] long* ReturnValue)</c>;</para></remarks>
        // method FlashVersion
        // IDL: HRESULT FlashVersion ([out, retval] long* ReturnValue);
        // VB6: Function FlashVersion As Long
        [DispId(132)]
        int FlashVersion();

        /// <summary><para><c>LoadMovie</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method LoadMovie</para></summary>
        /// <remarks><para>An original IDL definition of <c>LoadMovie</c> method was the following:  <c>HRESULT LoadMovie (int layer, BSTR url)</c>;</para></remarks>
        // method LoadMovie
        // IDL: HRESULT LoadMovie (int layer, BSTR url);
        // VB6: Sub LoadMovie (ByVal layer As Long, ByVal url As String)
        [DispId(142)]
        void LoadMovie(int layer, [MarshalAs(UnmanagedType.BStr)] string url);

        /// <summary><para><c>TGotoFrame</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TGotoFrame</para></summary>
        /// <remarks><para>An original IDL definition of <c>TGotoFrame</c> method was the following:  <c>HRESULT TGotoFrame (BSTR target, long FrameNum)</c>;</para></remarks>
        // method TGotoFrame
        // IDL: HRESULT TGotoFrame (BSTR target, long FrameNum);
        // VB6: Sub TGotoFrame (ByVal target As String, ByVal FrameNum As Long)
        [DispId(143)]
        void TGotoFrame([MarshalAs(UnmanagedType.BStr)] string target, int FrameNum);

        /// <summary><para><c>TGotoLabel</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TGotoLabel</para></summary>
        /// <remarks><para>An original IDL definition of <c>TGotoLabel</c> method was the following:  <c>HRESULT TGotoLabel (BSTR target, BSTR label)</c>;</para></remarks>
        // method TGotoLabel
        // IDL: HRESULT TGotoLabel (BSTR target, BSTR label);
        // VB6: Sub TGotoLabel (ByVal target As String, ByVal label As String)
        [DispId(144)]
        void TGotoLabel([MarshalAs(UnmanagedType.BStr)] string target, [MarshalAs(UnmanagedType.BStr)] string label);

        /// <summary><para><c>TCurrentFrame</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TCurrentFrame</para></summary>
        /// <remarks><para>An original IDL definition of <c>TCurrentFrame</c> method was the following:  <c>HRESULT TCurrentFrame (BSTR target, [out, retval] long* ReturnValue)</c>;</para></remarks>
        // method TCurrentFrame
        // IDL: HRESULT TCurrentFrame (BSTR target, [out, retval] long* ReturnValue);
        // VB6: Function TCurrentFrame (ByVal target As String) As Long
        [DispId(145)]
        int TCurrentFrame([MarshalAs(UnmanagedType.BStr)] string target);

        /// <summary><para><c>TCurrentLabel</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TCurrentLabel</para></summary>
        /// <remarks><para>An original IDL definition of <c>TCurrentLabel</c> method was the following:  <c>HRESULT TCurrentLabel (BSTR target, [out, retval] BSTR* ReturnValue)</c>;</para></remarks>
        // method TCurrentLabel
        // IDL: HRESULT TCurrentLabel (BSTR target, [out, retval] BSTR* ReturnValue);
        // VB6: Function TCurrentLabel (ByVal target As String) As String
        [DispId(146)]
        [return: MarshalAs(UnmanagedType.BStr)]
        string TCurrentLabel([MarshalAs(UnmanagedType.BStr)] string target);

        /// <summary><para><c>TPlay</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TPlay</para></summary>
        /// <remarks><para>An original IDL definition of <c>TPlay</c> method was the following:  <c>HRESULT TPlay (BSTR target)</c>;</para></remarks>
        // method TPlay
        // IDL: HRESULT TPlay (BSTR target);
        // VB6: Sub TPlay (ByVal target As String)
        [DispId(147)]
        void TPlay([MarshalAs(UnmanagedType.BStr)] string target);

        /// <summary><para><c>TStopPlay</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TStopPlay</para></summary>
        /// <remarks><para>An original IDL definition of <c>TStopPlay</c> method was the following:  <c>HRESULT TStopPlay (BSTR target)</c>;</para></remarks>
        // method TStopPlay
        // IDL: HRESULT TStopPlay (BSTR target);
        // VB6: Sub TStopPlay (ByVal target As String)
        [DispId(148)]
        void TStopPlay([MarshalAs(UnmanagedType.BStr)] string target);

        /// <summary><para><c>SetVariable</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method SetVariable</para></summary>
        /// <remarks><para>An original IDL definition of <c>SetVariable</c> method was the following:  <c>HRESULT SetVariable (BSTR name, BSTR value)</c>;</para></remarks>
        // method SetVariable
        // IDL: HRESULT SetVariable (BSTR name, BSTR value);
        // VB6: Sub SetVariable (ByVal name As String, ByVal value As String)
        [DispId(151)]
        void SetVariable([MarshalAs(UnmanagedType.BStr)] string name, [MarshalAs(UnmanagedType.BStr)] string value);

        /// <summary><para><c>GetVariable</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method GetVariable</para></summary>
        /// <remarks><para>An original IDL definition of <c>GetVariable</c> method was the following:  <c>HRESULT GetVariable (BSTR name, [out, retval] BSTR* ReturnValue)</c>;</para></remarks>
        // method GetVariable
        // IDL: HRESULT GetVariable (BSTR name, [out, retval] BSTR* ReturnValue);
        // VB6: Function GetVariable (ByVal name As String) As String
        [DispId(152)]
        [return: MarshalAs(UnmanagedType.BStr)]
        string GetVariable([MarshalAs(UnmanagedType.BStr)] string name);

        /// <summary><para><c>TSetProperty</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TSetProperty</para></summary>
        /// <remarks><para>An original IDL definition of <c>TSetProperty</c> method was the following:  <c>HRESULT TSetProperty (BSTR target, int property, BSTR value)</c>;</para></remarks>
        // method TSetProperty
        // IDL: HRESULT TSetProperty (BSTR target, int property, BSTR value);
        // VB6: Sub TSetProperty (ByVal target As String, ByVal property As Long, ByVal value As String)
        [DispId(153)]
        void TSetProperty([MarshalAs(UnmanagedType.BStr)] string target, int property, [MarshalAs(UnmanagedType.BStr)] string value);

        /// <summary><para><c>TGetProperty</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TGetProperty</para></summary>
        /// <remarks><para>An original IDL definition of <c>TGetProperty</c> method was the following:  <c>HRESULT TGetProperty (BSTR target, int property, [out, retval] BSTR* ReturnValue)</c>;</para></remarks>
        // method TGetProperty
        // IDL: HRESULT TGetProperty (BSTR target, int property, [out, retval] BSTR* ReturnValue);
        // VB6: Function TGetProperty (ByVal target As String, ByVal property As Long) As String
        [DispId(154)]
        [return: MarshalAs(UnmanagedType.BStr)]
        string TGetProperty([MarshalAs(UnmanagedType.BStr)] string target, int property);

        /// <summary><para><c>TCallFrame</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TCallFrame</para></summary>
        /// <remarks><para>An original IDL definition of <c>TCallFrame</c> method was the following:  <c>HRESULT TCallFrame (BSTR target, int FrameNum)</c>;</para></remarks>
        // method TCallFrame
        // IDL: HRESULT TCallFrame (BSTR target, int FrameNum);
        // VB6: Sub TCallFrame (ByVal target As String, ByVal FrameNum As Long)
        [DispId(155)]
        void TCallFrame([MarshalAs(UnmanagedType.BStr)] string target, int FrameNum);

        /// <summary><para><c>TCallLabel</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TCallLabel</para></summary>
        /// <remarks><para>An original IDL definition of <c>TCallLabel</c> method was the following:  <c>HRESULT TCallLabel (BSTR target, BSTR label)</c>;</para></remarks>
        // method TCallLabel
        // IDL: HRESULT TCallLabel (BSTR target, BSTR label);
        // VB6: Sub TCallLabel (ByVal target As String, ByVal label As String)
        [DispId(156)]
        void TCallLabel([MarshalAs(UnmanagedType.BStr)] string target, [MarshalAs(UnmanagedType.BStr)] string label);

        /// <summary><para><c>TSetPropertyNum</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TSetPropertyNum</para></summary>
        /// <remarks><para>An original IDL definition of <c>TSetPropertyNum</c> method was the following:  <c>HRESULT TSetPropertyNum (BSTR target, int property, double value)</c>;</para></remarks>
        // method TSetPropertyNum
        // IDL: HRESULT TSetPropertyNum (BSTR target, int property, double value);
        // VB6: Sub TSetPropertyNum (ByVal target As String, ByVal property As Long, ByVal value As Double)
        [DispId(157)]
        void TSetPropertyNum([MarshalAs(UnmanagedType.BStr)] string target, int property, double value);

        /// <summary><para><c>TGetPropertyNum</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TGetPropertyNum</para></summary>
        /// <remarks><para>An original IDL definition of <c>TGetPropertyNum</c> method was the following:  <c>HRESULT TGetPropertyNum (BSTR target, int property, [out, retval] double* ReturnValue)</c>;</para></remarks>
        // method TGetPropertyNum
        // IDL: HRESULT TGetPropertyNum (BSTR target, int property, [out, retval] double* ReturnValue);
        // VB6: Function TGetPropertyNum (ByVal target As String, ByVal property As Long) As Double
        [DispId(158)]
        double TGetPropertyNum([MarshalAs(UnmanagedType.BStr)] string target, int property);

        /// <summary><para><c>TGetPropertyAsNumber</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method TGetPropertyAsNumber</para></summary>
        /// <remarks><para>An original IDL definition of <c>TGetPropertyAsNumber</c> method was the following:  <c>HRESULT TGetPropertyAsNumber (BSTR target, int property, [out, retval] double* ReturnValue)</c>;</para></remarks>
        // method TGetPropertyAsNumber
        // IDL: HRESULT TGetPropertyAsNumber (BSTR target, int property, [out, retval] double* ReturnValue);
        // VB6: Function TGetPropertyAsNumber (ByVal target As String, ByVal property As Long) As Double
        [DispId(172)]
        double TGetPropertyAsNumber([MarshalAs(UnmanagedType.BStr)] string target, int property);

        /// <summary><para><c>EnforceLocalSecurity</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method EnforceLocalSecurity</para></summary>
        /// <remarks><para>An original IDL definition of <c>EnforceLocalSecurity</c> method was the following:  <c>HRESULT EnforceLocalSecurity (void)</c>;</para></remarks>
        // method EnforceLocalSecurity
        // IDL: HRESULT EnforceLocalSecurity (void);
        // VB6: Sub EnforceLocalSecurity
        [DispId(193)]
        void EnforceLocalSecurity();

        /// <summary><para><c>CallFunction</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method Call</para></summary>
        /// <remarks><para>An original IDL definition of <c>CallFunction</c> method was the following:  <c>HRESULT CallFunction (BSTR request, [out, retval] BSTR* ReturnValue)</c>;</para></remarks>
        // method Call
        // IDL: HRESULT CallFunction (BSTR request, [out, retval] BSTR* ReturnValue);
        // VB6: Function CallFunction (ByVal request As String) As String
        [DispId(198)]
        [return: MarshalAs(UnmanagedType.BStr)]
        string CallFunction([MarshalAs(UnmanagedType.BStr)] string request);

        /// <summary><para><c>SetReturnValue</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method SetReturnValue</para></summary>
        /// <remarks><para>An original IDL definition of <c>SetReturnValue</c> method was the following:  <c>HRESULT SetReturnValue (BSTR returnValue)</c>;</para></remarks>
        // method SetReturnValue
        // IDL: HRESULT SetReturnValue (BSTR returnValue);
        // VB6: Sub SetReturnValue (ByVal returnValue As String)
        [DispId(199)]
        void SetReturnValue([MarshalAs(UnmanagedType.BStr)] string returnValue);

        /// <summary><para><c>DisableLocalSecurity</c> method of <c>IShockwaveFlash</c> interface.  </para><para>method DisableLocalSecurity</para></summary>
        /// <remarks><para>An original IDL definition of <c>DisableLocalSecurity</c> method was the following:  <c>HRESULT DisableLocalSecurity (void)</c>;</para></remarks>
        // method DisableLocalSecurity
        // IDL: HRESULT DisableLocalSecurity (void);
        // VB6: Sub DisableLocalSecurity
        [DispId(200)]
        void DisableLocalSecurity();

        /// <summary><para><c>AlignMode</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property AlignMode</para></summary>
        /// <remarks><para>An original IDL definition of <c>AlignMode</c> property was the following:  <c>int AlignMode</c>;</para></remarks>
        // property AlignMode
        // IDL: int AlignMode;
        // VB6: AlignMode As Long
        int AlignMode {
            // IDL: HRESULT AlignMode ([out, retval] int* ReturnValue);
            // VB6: Function AlignMode As Long
            [DispId(121)]
            get;
            // IDL: HRESULT AlignMode (int value);
            // VB6: Sub AlignMode (ByVal value As Long)
            [DispId(121)]
            set;
        }

        /// <summary><para><c>AllowFullScreen</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property AllowFullScreen</para></summary>
        /// <remarks><para>An original IDL definition of <c>AllowFullScreen</c> property was the following:  <c>BSTR AllowFullScreen</c>;</para></remarks>
        // property AllowFullScreen
        // IDL: BSTR AllowFullScreen;
        // VB6: AllowFullScreen As String
        string AllowFullScreen {
            // IDL: HRESULT AllowFullScreen ([out, retval] BSTR* ReturnValue);
            // VB6: Function AllowFullScreen As String
            [DispId(202)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT AllowFullScreen (BSTR value);
            // VB6: Sub AllowFullScreen (ByVal value As String)
            [DispId(202)]
            set;
        }

        /// <summary><para><c>AllowNetworking</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property AllowNetworking</para></summary>
        /// <remarks><para>An original IDL definition of <c>AllowNetworking</c> property was the following:  <c>BSTR AllowNetworking</c>;</para></remarks>
        // property AllowNetworking
        // IDL: BSTR AllowNetworking;
        // VB6: AllowNetworking As String
        string AllowNetworking {
            // IDL: HRESULT AllowNetworking ([out, retval] BSTR* ReturnValue);
            // VB6: Function AllowNetworking As String
            [DispId(201)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT AllowNetworking (BSTR value);
            // VB6: Sub AllowNetworking (ByVal value As String)
            [DispId(201)]
            set;
        }

        /// <summary><para><c>AllowScriptAccess</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property AllowScriptAccess</para></summary>
        /// <remarks><para>An original IDL definition of <c>AllowScriptAccess</c> property was the following:  <c>BSTR AllowScriptAccess</c>;</para></remarks>
        // property AllowScriptAccess
        // IDL: BSTR AllowScriptAccess;
        // VB6: AllowScriptAccess As String
        string AllowScriptAccess {
            // IDL: HRESULT AllowScriptAccess ([out, retval] BSTR* ReturnValue);
            // VB6: Function AllowScriptAccess As String
            [DispId(171)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT AllowScriptAccess (BSTR value);
            // VB6: Sub AllowScriptAccess (ByVal value As String)
            [DispId(171)]
            set;
        }

        /// <summary><para><c>BackgroundColor</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property BackgroundColor</para></summary>
        /// <remarks><para>An original IDL definition of <c>BackgroundColor</c> property was the following:  <c>long BackgroundColor</c>;</para></remarks>
        // property BackgroundColor
        // IDL: long BackgroundColor;
        // VB6: BackgroundColor As Long
        int BackgroundColor {
            // IDL: HRESULT BackgroundColor ([out, retval] long* ReturnValue);
            // VB6: Function BackgroundColor As Long
            [DispId(123)]
            get;
            // IDL: HRESULT BackgroundColor (long value);
            // VB6: Sub BackgroundColor (ByVal value As Long)
            [DispId(123)]
            set;
        }

        /// <summary><para><c>Base</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Base</para></summary>
        /// <remarks><para>An original IDL definition of <c>Base</c> property was the following:  <c>BSTR Base</c>;</para></remarks>
        // property Base
        // IDL: BSTR Base;
        // VB6: Base As String
        string Base {
            // IDL: HRESULT Base ([out, retval] BSTR* ReturnValue);
            // VB6: Function Base As String
            [DispId(136)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT Base (BSTR value);
            // VB6: Sub Base (ByVal value As String)
            [DispId(136)]
            set;
        }

        /// <summary><para><c>BGColor</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property BGColor</para></summary>
        /// <remarks><para>An original IDL definition of <c>BGColor</c> property was the following:  <c>BSTR BGColor</c>;</para></remarks>
        // property BGColor
        // IDL: BSTR BGColor;
        // VB6: BGColor As String
        string BGColor {
            // IDL: HRESULT BGColor ([out, retval] BSTR* ReturnValue);
            // VB6: Function BGColor As String
            [DispId(140)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT BGColor (BSTR value);
            // VB6: Sub BGColor (ByVal value As String)
            [DispId(140)]
            set;
        }

        /// <summary><para><c>DeviceFont</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property DeviceFont</para></summary>
        /// <remarks><para>An original IDL definition of <c>DeviceFont</c> property was the following:  <c>VARIANT_BOOL DeviceFont</c>;</para></remarks>
        // property DeviceFont
        // IDL: VARIANT_BOOL DeviceFont;
        // VB6: DeviceFont As Boolean
        bool DeviceFont {
            // IDL: HRESULT DeviceFont ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function DeviceFont As Boolean
            [DispId(138)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT DeviceFont (VARIANT_BOOL value);
            // VB6: Sub DeviceFont (ByVal value As Boolean)
            [DispId(138)]
            set;
        }

        /// <summary><para><c>EmbedMovie</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property EmbedMovie</para></summary>
        /// <remarks><para>An original IDL definition of <c>EmbedMovie</c> property was the following:  <c>VARIANT_BOOL EmbedMovie</c>;</para></remarks>
        // property EmbedMovie
        // IDL: VARIANT_BOOL EmbedMovie;
        // VB6: EmbedMovie As Boolean
        bool EmbedMovie {
            // IDL: HRESULT EmbedMovie ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function EmbedMovie As Boolean
            [DispId(139)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT EmbedMovie (VARIANT_BOOL value);
            // VB6: Sub EmbedMovie (ByVal value As Boolean)
            [DispId(139)]
            set;
        }

        /// <summary><para><c>FlashVars</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property FlashVars</para></summary>
        /// <remarks><para>An original IDL definition of <c>FlashVars</c> property was the following:  <c>BSTR FlashVars</c>;</para></remarks>
        // property FlashVars
        // IDL: BSTR FlashVars;
        // VB6: FlashVars As String
        string FlashVars {
            // IDL: HRESULT FlashVars ([out, retval] BSTR* ReturnValue);
            // VB6: Function FlashVars As String
            [DispId(170)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT FlashVars (BSTR value);
            // VB6: Sub FlashVars (ByVal value As String)
            [DispId(170)]
            set;
        }

        /// <summary><para><c>FrameNum</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property FrameNum</para></summary>
        /// <remarks><para>An original IDL definition of <c>FrameNum</c> property was the following:  <c>long FrameNum</c>;</para></remarks>
        // property FrameNum
        // IDL: long FrameNum;
        // VB6: FrameNum As Long
        int FrameNum {
            // IDL: HRESULT FrameNum ([out, retval] long* ReturnValue);
            // VB6: Function FrameNum As Long
            [DispId(107)]
            get;
            // IDL: HRESULT FrameNum (long value);
            // VB6: Sub FrameNum (ByVal value As Long)
            [DispId(107)]
            set;
        }

        /// <summary><para><c>InlineData</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property inline-data</para></summary>
        /// <remarks><para>An original IDL definition of <c>InlineData</c> property was the following:  <c>IUnknown* InlineData</c>;</para></remarks>
        // property inline-data
        // IDL: IUnknown* InlineData;
        // VB6: InlineData As IUnknown
        object InlineData {
            // IDL: HRESULT InlineData ([out, retval] IUnknown** ReturnValue);
            // VB6: Function InlineData As IUnknown
            [DispId(191)]
            [return: MarshalAs(UnmanagedType.IUnknown)]
            get;
            // IDL: HRESULT InlineData (IUnknown* value);
            // VB6: Sub InlineData (ByVal value As IUnknown)
            [DispId(191)]
            set;
        }

        /// <summary><para><c>Loop</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Loop</para></summary>
        /// <remarks><para>An original IDL definition of <c>Loop</c> property was the following:  <c>VARIANT_BOOL Loop</c>;</para></remarks>
        // property Loop
        // IDL: VARIANT_BOOL Loop;
        // VB6: Loop As Boolean
        bool Loop {
            // IDL: HRESULT Loop ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function Loop As Boolean
            [DispId(106)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT Loop (VARIANT_BOOL value);
            // VB6: Sub Loop (ByVal value As Boolean)
            [DispId(106)]
            set;
        }

        /// <summary><para><c>Menu</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Menu</para></summary>
        /// <remarks><para>An original IDL definition of <c>Menu</c> property was the following:  <c>VARIANT_BOOL Menu</c>;</para></remarks>
        // property Menu
        // IDL: VARIANT_BOOL Menu;
        // VB6: Menu As Boolean
        bool Menu {
            // IDL: HRESULT Menu ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function Menu As Boolean
            [DispId(135)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT Menu (VARIANT_BOOL value);
            // VB6: Sub Menu (ByVal value As Boolean)
            [DispId(135)]
            set;
        }

        /// <summary><para><c>Movie</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Movie</para></summary>
        /// <remarks><para>An original IDL definition of <c>Movie</c> property was the following:  <c>BSTR Movie</c>;</para></remarks>
        // property Movie
        // IDL: BSTR Movie;
        // VB6: Movie As String
        string Movie {
            // IDL: HRESULT Movie ([out, retval] BSTR* ReturnValue);
            // VB6: Function Movie As String
            [DispId(102)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT Movie (BSTR value);
            // VB6: Sub Movie (ByVal value As String)
            [DispId(102)]
            set;
        }

        /// <summary><para><c>MovieData</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property MovieData</para></summary>
        /// <remarks><para>An original IDL definition of <c>MovieData</c> property was the following:  <c>BSTR MovieData</c>;</para></remarks>
        // property MovieData
        // IDL: BSTR MovieData;
        // VB6: MovieData As String
        string MovieData {
            // IDL: HRESULT MovieData ([out, retval] BSTR* ReturnValue);
            // VB6: Function MovieData As String
            [DispId(190)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT MovieData (BSTR value);
            // VB6: Sub MovieData (ByVal value As String)
            [DispId(190)]
            set;
        }

        /// <summary><para><c>Playing</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Playing</para></summary>
        /// <remarks><para>An original IDL definition of <c>Playing</c> property was the following:  <c>VARIANT_BOOL Playing</c>;</para></remarks>
        // property Playing
        // IDL: VARIANT_BOOL Playing;
        // VB6: Playing As Boolean
        bool Playing {
            // IDL: HRESULT Playing ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function Playing As Boolean
            [DispId(125)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT Playing (VARIANT_BOOL value);
            // VB6: Sub Playing (ByVal value As Boolean)
            [DispId(125)]
            set;
        }

        /// <summary><para><c>Profile</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Profile</para></summary>
        /// <remarks><para>An original IDL definition of <c>Profile</c> property was the following:  <c>VARIANT_BOOL Profile</c>;</para></remarks>
        // property Profile
        // IDL: VARIANT_BOOL Profile;
        // VB6: Profile As Boolean
        bool Profile {
            // IDL: HRESULT Profile ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function Profile As Boolean
            [DispId(194)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT Profile (VARIANT_BOOL value);
            // VB6: Sub Profile (ByVal value As Boolean)
            [DispId(194)]
            set;
        }

        /// <summary><para><c>ProfileAddress</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property ProfileAddress</para></summary>
        /// <remarks><para>An original IDL definition of <c>ProfileAddress</c> property was the following:  <c>BSTR ProfileAddress</c>;</para></remarks>
        // property ProfileAddress
        // IDL: BSTR ProfileAddress;
        // VB6: ProfileAddress As String
        string ProfileAddress {
            // IDL: HRESULT ProfileAddress ([out, retval] BSTR* ReturnValue);
            // VB6: Function ProfileAddress As String
            [DispId(195)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT ProfileAddress (BSTR value);
            // VB6: Sub ProfileAddress (ByVal value As String)
            [DispId(195)]
            set;
        }

        /// <summary><para><c>ProfilePort</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property ProfilePort</para></summary>
        /// <remarks><para>An original IDL definition of <c>ProfilePort</c> property was the following:  <c>long ProfilePort</c>;</para></remarks>
        // property ProfilePort
        // IDL: long ProfilePort;
        // VB6: ProfilePort As Long
        int ProfilePort {
            // IDL: HRESULT ProfilePort ([out, retval] long* ReturnValue);
            // VB6: Function ProfilePort As Long
            [DispId(196)]
            get;
            // IDL: HRESULT ProfilePort (long value);
            // VB6: Sub ProfilePort (ByVal value As Long)
            [DispId(196)]
            set;
        }

        /// <summary><para><c>Quality</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Quality</para></summary>
        /// <remarks><para>An original IDL definition of <c>Quality</c> property was the following:  <c>int Quality</c>;</para></remarks>
        // property Quality
        // IDL: int Quality;
        // VB6: Quality As Long
        int Quality {
            // IDL: HRESULT Quality ([out, retval] int* ReturnValue);
            // VB6: Function Quality As Long
            [DispId(105)]
            get;
            // IDL: HRESULT Quality (int value);
            // VB6: Sub Quality (ByVal value As Long)
            [DispId(105)]
            set;
        }

        /// <summary><para><c>Quality2</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Quality2</para></summary>
        /// <remarks><para>An original IDL definition of <c>Quality2</c> property was the following:  <c>BSTR Quality2</c>;</para></remarks>
        // property Quality2
        // IDL: BSTR Quality2;
        // VB6: Quality2 As String
        string Quality2 {
            // IDL: HRESULT Quality2 ([out, retval] BSTR* ReturnValue);
            // VB6: Function Quality2 As String
            [DispId(141)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT Quality2 (BSTR value);
            // VB6: Sub Quality2 (ByVal value As String)
            [DispId(141)]
            set;
        }

        /// <summary><para><c>ReadyState</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property ReadyState</para></summary>
        /// <remarks><para>An original IDL definition of <c>ReadyState</c> property was the following:  <c>long ReadyState</c>;</para></remarks>
        // property ReadyState
        // IDL: long ReadyState;
        // VB6: ReadyState As Long
        int ReadyState {
            // IDL: HRESULT ReadyState ([out, retval] long* ReturnValue);
            // VB6: Function ReadyState As Long
            [DispId(-525)]
            get;
        }

        /// <summary><para><c>SAlign</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property SAlign</para></summary>
        /// <remarks><para>An original IDL definition of <c>SAlign</c> property was the following:  <c>BSTR SAlign</c>;</para></remarks>
        // property SAlign
        // IDL: BSTR SAlign;
        // VB6: SAlign As String
        string SAlign {
            // IDL: HRESULT SAlign ([out, retval] BSTR* ReturnValue);
            // VB6: Function SAlign As String
            [DispId(134)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT SAlign (BSTR value);
            // VB6: Sub SAlign (ByVal value As String)
            [DispId(134)]
            set;
        }

        /// <summary><para><c>Scale</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property Scale</para></summary>
        /// <remarks><para>An original IDL definition of <c>Scale</c> property was the following:  <c>BSTR Scale</c>;</para></remarks>
        // property Scale
        // IDL: BSTR Scale;
        // VB6: Scale As String
        string Scale {
            // IDL: HRESULT Scale ([out, retval] BSTR* ReturnValue);
            // VB6: Function Scale As String
            [DispId(137)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT Scale (BSTR value);
            // VB6: Sub Scale (ByVal value As String)
            [DispId(137)]
            set;
        }

        /// <summary><para><c>ScaleMode</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property ScaleMode</para></summary>
        /// <remarks><para>An original IDL definition of <c>ScaleMode</c> property was the following:  <c>int ScaleMode</c>;</para></remarks>
        // property ScaleMode
        // IDL: int ScaleMode;
        // VB6: ScaleMode As Long
        int ScaleMode {
            // IDL: HRESULT ScaleMode ([out, retval] int* ReturnValue);
            // VB6: Function ScaleMode As Long
            [DispId(120)]
            get;
            // IDL: HRESULT ScaleMode (int value);
            // VB6: Sub ScaleMode (ByVal value As Long)
            [DispId(120)]
            set;
        }

        /// <summary><para><c>SeamlessTabbing</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property SeamlessTabbing</para></summary>
        /// <remarks><para>An original IDL definition of <c>SeamlessTabbing</c> property was the following:  <c>VARIANT_BOOL SeamlessTabbing</c>;</para></remarks>
        // property SeamlessTabbing
        // IDL: VARIANT_BOOL SeamlessTabbing;
        // VB6: SeamlessTabbing As Boolean
        bool SeamlessTabbing {
            // IDL: HRESULT SeamlessTabbing ([out, retval] VARIANT_BOOL* ReturnValue);
            // VB6: Function SeamlessTabbing As Boolean
            [DispId(192)]
            [return: MarshalAs(UnmanagedType.VariantBool)]
            get;
            // IDL: HRESULT SeamlessTabbing (VARIANT_BOOL value);
            // VB6: Sub SeamlessTabbing (ByVal value As Boolean)
            [DispId(192)]
            set;
        }

        /// <summary><para><c>SWRemote</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property SWRemote</para></summary>
        /// <remarks><para>An original IDL definition of <c>SWRemote</c> property was the following:  <c>BSTR SWRemote</c>;</para></remarks>
        // property SWRemote
        // IDL: BSTR SWRemote;
        // VB6: SWRemote As String
        string SWRemote {
            // IDL: HRESULT SWRemote ([out, retval] BSTR* ReturnValue);
            // VB6: Function SWRemote As String
            [DispId(159)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT SWRemote (BSTR value);
            // VB6: Sub SWRemote (ByVal value As String)
            [DispId(159)]
            set;
        }

        /// <summary><para><c>TotalFrames</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property TotalFrames</para></summary>
        /// <remarks><para>An original IDL definition of <c>TotalFrames</c> property was the following:  <c>long TotalFrames</c>;</para></remarks>
        // property TotalFrames
        // IDL: long TotalFrames;
        // VB6: TotalFrames As Long
        int TotalFrames {
            // IDL: HRESULT TotalFrames ([out, retval] long* ReturnValue);
            // VB6: Function TotalFrames As Long
            [DispId(124)]
            get;
        }

        /// <summary><para><c>WMode</c> property of <c>IShockwaveFlash</c> interface.  </para><para>property WMode</para></summary>
        /// <remarks><para>An original IDL definition of <c>WMode</c> property was the following:  <c>BSTR WMode</c>;</para></remarks>
        // property WMode
        // IDL: BSTR WMode;
        // VB6: WMode As String
        string WMode {
            // IDL: HRESULT WMode ([out, retval] BSTR* ReturnValue);
            // VB6: Function WMode As String
            [DispId(133)]
            [return: MarshalAs(UnmanagedType.BStr)]
            get;
            // IDL: HRESULT WMode (BSTR value);
            // VB6: Sub WMode (ByVal value As String)
            [DispId(133)]
            set;
        }
    }

    /// <summary><para><c>IDispatchEx</c> interface.</para></summary>
    [Guid("A6EF9860-C720-11D0-9337-00A0C90DCAA9")]
    [ComImport]
    [TypeLibType((short)4096)]
    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IDispatchEx {
        /// <summary><para><c>GetDispID</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>GetDispID</c> method was the following:  <c>HRESULT GetDispID (BSTR bstrName, unsigned long grfdex, [out] long* pid)</c>;</para></remarks>
        // IDL: HRESULT GetDispID (BSTR bstrName, unsigned long grfdex, [out] long* pid);
        // VB6: Sub GetDispID (ByVal bstrName As String, ByVal grfdex As Long, pid As Long)
        [DispId(1610743808)]
        void GetDispID([MarshalAs(UnmanagedType.BStr)] string bstrName, uint grfdex, [Out] out int pid);

        /// <summary><para><c>RemoteInvokeEx</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>RemoteInvokeEx</c> method was the following:  <c>HRESULT RemoteInvokeEx (long id, unsigned long lcid, unsigned long dwFlags, [in] Interop.stdole.DISPPARAMS* pdp, [out] VARIANT* pvarRes, [out] Interop.stdole.EXCEPINFO* pei, IServiceProvider* pspCaller, unsigned int cvarRefArg, [in] unsigned int* rgiRefArg, [in, out] VARIANT* rgvarRefArg)</c>;</para></remarks>
        // IDL: HRESULT RemoteInvokeEx (long id, unsigned long lcid, unsigned long dwFlags, [in] Interop.stdole.DISPPARAMS* pdp, [out] VARIANT* pvarRes, [out] Interop.stdole.EXCEPINFO* pei, IServiceProvider* pspCaller, unsigned int cvarRefArg, [in] unsigned int* rgiRefArg, [in, out] VARIANT* rgvarRefArg);
        // VB6: Sub RemoteInvokeEx (ByVal id As Long, ByVal lcid As Long, ByVal dwFlags As Long, pdp As Interop.stdole.DISPPARAMS, pvarRes As Any, pei As Interop.stdole.EXCEPINFO, ByVal pspCaller As IServiceProvider, ByVal cvarRefArg As Long, rgiRefArg As Long, rgvarRefArg As Any)
        //[DispId(1610743809)]
        //void RemoteInvokeEx (int id, uint lcid, uint dwFlags, [In] ref Interop.stdole.DISPPARAMS pdp, [Out] out object pvarRes, [Out] out Interop.stdole.EXCEPINFO pei, IServiceProvider pspCaller, uint cvarRefArg, [In] ref uint rgiRefArg, [In, Out] ref object rgvarRefArg);

        /// <summary><para><c>DeleteMemberByName</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>DeleteMemberByName</c> method was the following:  <c>HRESULT DeleteMemberByName (BSTR bstrName, unsigned long grfdex)</c>;</para></remarks>
        // IDL: HRESULT DeleteMemberByName (BSTR bstrName, unsigned long grfdex);
        // VB6: Sub DeleteMemberByName (ByVal bstrName As String, ByVal grfdex As Long)
        [DispId(1610743810)]
        void DeleteMemberByName([MarshalAs(UnmanagedType.BStr)] string bstrName, uint grfdex);

        /// <summary><para><c>DeleteMemberByDispID</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>DeleteMemberByDispID</c> method was the following:  <c>HRESULT DeleteMemberByDispID (long id)</c>;</para></remarks>
        // IDL: HRESULT DeleteMemberByDispID (long id);
        // VB6: Sub DeleteMemberByDispID (ByVal id As Long)
        [DispId(1610743811)]
        void DeleteMemberByDispID(int id);

        /// <summary><para><c>GetMemberProperties</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>GetMemberProperties</c> method was the following:  <c>HRESULT GetMemberProperties (long id, unsigned long grfdexFetch, [out] unsigned long* pgrfdex)</c>;</para></remarks>
        // IDL: HRESULT GetMemberProperties (long id, unsigned long grfdexFetch, [out] unsigned long* pgrfdex);
        // VB6: Sub GetMemberProperties (ByVal id As Long, ByVal grfdexFetch As Long, pgrfdex As Long)
        [DispId(1610743812)]
        void GetMemberProperties(int id, uint grfdexFetch, [Out] out uint pgrfdex);

        /// <summary><para><c>GetMemberName</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>GetMemberName</c> method was the following:  <c>HRESULT GetMemberName (long id, [out] BSTR* pbstrName)</c>;</para></remarks>
        // IDL: HRESULT GetMemberName (long id, [out] BSTR* pbstrName);
        // VB6: Sub GetMemberName (ByVal id As Long, pbstrName As String)
        [DispId(1610743813)]
        void GetMemberName(int id, [Out, MarshalAs(UnmanagedType.BStr)] out string pbstrName);

        /// <summary><para><c>GetNextDispID</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>GetNextDispID</c> method was the following:  <c>HRESULT GetNextDispID (unsigned long grfdex, long id, [out] long* pid)</c>;</para></remarks>
        // IDL: HRESULT GetNextDispID (unsigned long grfdex, long id, [out] long* pid);
        // VB6: Sub GetNextDispID (ByVal grfdex As Long, ByVal id As Long, pid As Long)
        [DispId(1610743814)]
        void GetNextDispID(uint grfdex, int id, [Out] out int pid);

        /// <summary><para><c>GetNameSpaceParent</c> method of <c>IDispatchEx</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>GetNameSpaceParent</c> method was the following:  <c>HRESULT GetNameSpaceParent ([out] IUnknown** ppunk)</c>;</para></remarks>
        // IDL: HRESULT GetNameSpaceParent ([out] IUnknown** ppunk);
        // VB6: Sub GetNameSpaceParent (ppunk As IUnknown)
        [DispId(1610743815)]
        void GetNameSpaceParent([Out, MarshalAs(UnmanagedType.IUnknown)] out object ppunk);
    }

    /// <summary><para><c>IFlashFactory</c> interface.  </para><para>IFlashFactory Interface</para></summary>
    // IFlashFactory Interface
    [Guid("D27CDB70-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [TypeLibType((short)0)]
    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IFlashFactory {
    }

    /// <summary><para><c>IFlashObjectInterface</c> interface.  </para><para>IFlashObjectInterface Interface</para></summary>
    // IFlashObjectInterface Interface
    [Guid("D27CDB72-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [TypeLibType((short)4096)]
    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IFlashObjectInterface {
    }

    /// <summary><para><c>IServiceProvider</c> interface.</para></summary>
    [Guid("6D5140C1-7436-11CE-8034-00AA006009FA")]
    [ComImport]
    [TypeLibType((short)0)]
    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IServiceProvider {
        /// <summary><para><c>RemoteQueryService</c> method of <c>IServiceProvider</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>RemoteQueryService</c> method was the following:  <c>HRESULT RemoteQueryService ([in] Interop.stdole.GUID* guidService, [in] Interop.stdole.GUID* riid, [out] IUnknown** ppvObject)</c>;</para></remarks>
        // IDL: HRESULT RemoteQueryService ([in] Interop.stdole.GUID* guidService, [in] Interop.stdole.GUID* riid, [out] IUnknown** ppvObject);
        // VB6: Sub RemoteQueryService (guidService As Interop.stdole.GUID, riid As Interop.stdole.GUID, ppvObject As IUnknown)
        //void RemoteQueryService ([In] ref Interop.stdole.GUID guidService, [In] ref Interop.stdole.GUID riid, [Out, MarshalAs(UnmanagedType.IUnknown)] out object ppvObject);
    }

    /// <summary><para><c>FlashObjectInterface</c> interface.IFlashObjectInterface Interface</para></summary>
    // IFlashObjectInterface Interface
    [Guid("D27CDB72-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [CoClass(typeof(FlashObjectInterfaceClass))]
    public interface IIFlashObjectInterface : IFlashObjectInterface {
    }

    /// <summary><para><c>FlashObjectInterfaceClass</c> class.  </para><para>IFlashObjectInterface Interface</para></summary>
    /// <remarks>The following sample shows how to use FlashObjectInterfaceClass class.  You should simply create new class instance and cast it to FlashObjectInterface interface.  After this you can call interface methods and access its properties: <code>
    /// FlashObjectInterface A = (FlashObjectInterface) new FlashObjectInterfaceClass();
    /// A.[method name]();  A.[property name] = [value]; [variable] = A.[property name];
    /// </code></remarks>
    // IFlashObjectInterface Interface
    [Guid("D27CDB71-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [TypeLibType((short)2)]
    [ClassInterface(ClassInterfaceType.None)]
    public class FlashObjectInterfaceClass // : IFlashObjectInterface, FlashObjectInterface
    {
    }

    /// <summary><para><c>FlashProp</c> interface.Macromedia Flash Player Properties</para></summary>
    // Macromedia Flash Player Properties
    // [ComImport, Guid( <Undefined> )] 
    /*[CoClass(typeof(FlashPropClass))]
    public interface FlashProp
    {
    }*/

    /// <summary><para><c>FlashPropClass</c> class.  </para><para>Macromedia Flash Player Properties</para></summary>
    /// <remarks>The following sample shows how to use FlashPropClass class.  You should simply create new class instance and cast it to FlashProp interface.  After this you can call interface methods and access its properties: <code>
    /// FlashProp A = (FlashProp) new FlashPropClass();
    /// A.[method name]();  A.[property name] = [value]; [variable] = A.[property name];
    /// </code></remarks>
    // Macromedia Flash Player Properties
    [Guid("1171A62F-05D2-11D1-83FC-00A0C9089C5A")]
    [ComImport]
    [TypeLibType((short)2)]
    [ClassInterface(ClassInterfaceType.None)]
    public class FlashPropClass // : FlashProp
    {
    }

    /// <summary><para><c>ShockwaveFlash</c> interface.Shockwave Flash</para></summary>
    // Shockwave Flash
    [Guid("D27CDB6C-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [CoClass(typeof(ShockwaveFlashClass))]
    public interface IIShockwaveFlash : IShockwaveFlash {
    }

    /// <summary><para><c>ShockwaveFlashClass</c> class.  </para><para>Shockwave Flash</para></summary>
    /// <remarks>The following sample shows how to use ShockwaveFlashClass class.  You should simply create new class instance and cast it to ShockwaveFlash interface.  After this you can call interface methods and access its properties: <code>
    /// ShockwaveFlash A = (ShockwaveFlash) new ShockwaveFlashClass();
    /// A.[method name]();  A.[property name] = [value]; [variable] = A.[property name];
    /// </code></remarks>
    // Shockwave Flash
    [Guid("D27CDB6E-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [TypeLibType((short)2)]
    [ClassInterface(ClassInterfaceType.None)]
    [ComSourceInterfaces("_IShockwaveFlashEvents")]
    public class ShockwaveFlashClass // : IShockwaveFlash, ShockwaveFlash, _IShockwaveFlashEvents_Event
    {
    }
    /// <summary><para><c>_IShockwaveFlashEvents</c> interface.  </para><para>Event interface for Shockwave Flash</para></summary>
    // Event interface for Shockwave Flash
    [Guid("D27CDB6D-AE6D-11CF-96B8-444553540000")]
    [ComImport]
    [TypeLibType((short)4112)]
    [InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IIShockwaveFlashEvents {
        /// <summary><para><c>OnReadyStateChange</c> method of <c>_IShockwaveFlashEvents</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>OnReadyStateChange</c> method was the following:  <c>HRESULT OnReadyStateChange (long newState)</c>;</para></remarks>
        // IDL: HRESULT OnReadyStateChange (long newState);
        // VB6: Sub OnReadyStateChange (ByVal newState As Long)
        [DispId(-609)]
        void OnReadyStateChange(int newState);

        /// <summary><para><c>OnProgress</c> method of <c>_IShockwaveFlashEvents</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>OnProgress</c> method was the following:  <c>HRESULT OnProgress (long percentDone)</c>;</para></remarks>
        // IDL: HRESULT OnProgress (long percentDone);
        // VB6: Sub OnProgress (ByVal percentDone As Long)
        [DispId(1958)]
        void OnProgress(int percentDone);

        /// <summary><para><c>FSCommand</c> method of <c>_IShockwaveFlashEvents</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>FSCommand</c> method was the following:  <c>HRESULT FSCommand (BSTR command, BSTR args)</c>;</para></remarks>
        // IDL: HRESULT FSCommand (BSTR command, BSTR args);
        // VB6: Sub FSCommand (ByVal command As String, ByVal args As String)
        [DispId(150)]
        void FSCommand([MarshalAs(UnmanagedType.BStr)] string command, [MarshalAs(UnmanagedType.BStr)] string args);

        /// <summary><para><c>FlashCall</c> method of <c>_IShockwaveFlashEvents</c> interface.</para></summary>
        /// <remarks><para>An original IDL definition of <c>FlashCall</c> method was the following:  <c>HRESULT FlashCall (BSTR request)</c>;</para></remarks>
        // IDL: HRESULT FlashCall (BSTR request);
        // VB6: Sub FlashCall (ByVal request As String)
        [DispId(197)]
        void FlashCall([MarshalAs(UnmanagedType.BStr)] string request);
    }
}
